package com.iivan.imbg.dao.model;

import com.iivan.imbg.dao.model.Test;
import com.iivan.imbg.dao.model.TestCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Tue Mar 18 12:06:46 CST 2014
     */
    int countByExample(TestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Tue Mar 18 12:06:46 CST 2014
     */
    int deleteByExample(TestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Tue Mar 18 12:06:46 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Tue Mar 18 12:06:46 CST 2014
     */
    int insert(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Tue Mar 18 12:06:46 CST 2014
     */
    int insertSelective(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Tue Mar 18 12:06:46 CST 2014
     */
    List<Test> selectByExample(TestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Tue Mar 18 12:06:46 CST 2014
     */
    int updateByExampleSelective(@Param("record") Test record, @Param("example") TestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Tue Mar 18 12:06:46 CST 2014
     */
    int updateByExample(@Param("record") Test record, @Param("example") TestCriteria example);
}